package calculator

import (
	"fmt"
	"math"
	"time"

	"github.com/paanipoorie/alternative-credit-engine/apps/api/pkg/domain"
)

// Weights for the transparent prototype scoring framework
const (
	WeightCashFlowStability   = 0.30
	WeightIncomeConsistency   = 0.20
	WeightPaymentDiscipline   = 0.20
	WeightActivityContinuity  = 0.15
	WeightFinancialResilience = 0.15
)

// Assess calculates the complete Alternative Credit Profile deterministically
func Assess(customerID, customerName, personaType string, evidenceList []domain.CanonicalEvidence, declared ...*domain.DeclaredProfile) domain.AssessmentProfile {
	features := CalculateFeatures(evidenceList)

	// 1. Calculate 5 Behavioral Dimensions (each 0 - 100)
	dimensions := CalculateDimensions(features, evidenceList)

	// 2. Composite Behavioral Score: B = 0.30*C + 0.20*I + 0.20*P + 0.15*A + 0.15*R
	bScore := (WeightCashFlowStability * dimensions.CashFlowStability) +
		(WeightIncomeConsistency * dimensions.IncomeConsistency) +
		(WeightPaymentDiscipline * dimensions.PaymentDiscipline) +
		(WeightActivityContinuity * dimensions.ActivityContinuity) +
		(WeightFinancialResilience * dimensions.FinancialResilience)

	bScore = clamp(bScore, 0.0, 100.0)
	// Round to 4 decimal places to prevent IEEE 754 float representation drift (e.g. 76.74999999999999 -> 76.75)
	bScore = math.Round(bScore*10000.0) / 10000.0

	// 3. Map to displayed 300 - 900 score: Score = round(300 + 6 * B)
	finalScore := int(math.Round(300.0 + (6.0 * bScore)))
	if finalScore < 300 {
		finalScore = 300
	}
	if finalScore > 900 {
		finalScore = 900
	}

	// 4. Determine Risk Band
	riskBand := "Higher Risk"
	if finalScore >= 750 {
		riskBand = "Low Risk"
	} else if finalScore >= 670 {
		riskBand = "Low-Moderate Risk"
	} else if finalScore >= 580 {
		riskBand = "Moderate Risk"
	}

	// 5. Calculate Confidence and Data Coverage
	confidenceScore := CalculateConfidence(evidenceList)
	coverageScore, coverageBreakdown := CalculateCoverage(evidenceList)

	// 6. Generate Grounded Explainable Reasons
	positiveFactors, attentionFactors := GenerateExplainableReasons(features, dimensions, evidenceList)

	// 7. Phase 5: Build Observed Profile & Financial Reconciliation
	var decProfile *domain.DeclaredProfile
	if len(declared) > 0 && declared[0] != nil {
		decProfile = declared[0]
	}
	observedProfile := BuildObservedProfile(features, evidenceList)
	reconciliation := ReconcileProfiles(decProfile, observedProfile, features, evidenceList)

	// 8. Phase 5: Deterministic Assessment Flags & Underwriting Band
	assessmentFlags := GenerateAssessmentFlags(decProfile, features, dimensions, evidenceList, reconciliation)
	assessmentBand := DetermineAssessmentBand(finalScore, confidenceScore, coverageScore, assessmentFlags, evidenceList)

	// 9. Phase 5: Evidence Contribution Traces
	evidenceTraces := GenerateEvidenceTraces(features, dimensions, evidenceList)

	// 10. Collect Provenance
	var provenanceList []domain.ProvenanceItem
	for _, ev := range evidenceList {
		provenanceList = append(provenanceList, ev.Provenance)
	}

	dimWeights := map[string]float64{
		"cash_flow_stability":  WeightCashFlowStability,
		"income_consistency":   WeightIncomeConsistency,
		"payment_discipline":   WeightPaymentDiscipline,
		"activity_continuity":  WeightActivityContinuity,
		"financial_resilience": WeightFinancialResilience,
	}

	return domain.AssessmentProfile{
		AssessmentID:      fmt.Sprintf("ASM-%d", time.Now().UnixNano()/1000000),
		CustomerID:        customerID,
		CustomerName:      customerName,
		PersonaType:       personaType,
		DeclaredProfile:   decProfile,
		ObservedProfile:   observedProfile,
		Reconciliation:    reconciliation,
		BehavioralScore:   math.Round(bScore*100) / 100,
		FinalScore:        finalScore,
		RiskBand:          riskBand,
		AssessmentBand:    assessmentBand,
		ConfidenceScore:   confidenceScore,
		DataCoverageScore: coverageScore,
		Dimensions:        dimensions,
		DimensionWeights:  dimWeights,
		PositiveFactors:   positiveFactors,
		AttentionFactors:  attentionFactors,
		Features:          features,
		Provenance:        provenanceList,
		EvidenceTraces:    evidenceTraces,
		AssessmentFlags:   assessmentFlags,
		CoverageBreakdown: coverageBreakdown,
		CreatedAt:         time.Now(),
		Disclaimer:        "This score is generated by a transparent prototype underwriting support framework. Missing data sources reduce data coverage and confidence rather than penalizing credit score. In production, this framework would be replaced with a calibrated statistical/ML model trained on historical repayment outcomes.",
	}
}

// CalculateDimensions computes the five 0-100 behavioral dimension scores
func CalculateDimensions(f domain.DerivedFeatures, evidenceList []domain.CanonicalEvidence) domain.BehavioralDimensions {
	hasUPI := false
	hasGig := false
	hasUtility := false
	hasGST := false

	for _, ev := range evidenceList {
		switch ev.SourceType {
		case domain.SourceUPI:
			if len(ev.UPITransactions) > 0 {
				hasUPI = true
			}
		case domain.SourceGig:
			if len(ev.GigPayouts) > 0 {
				hasGig = true
			}
		case domain.SourceUtility:
			if len(ev.UtilityPayments) > 0 {
				hasUtility = true
			}
		case domain.SourceGST:
			if len(ev.GSTRRecords) > 0 {
				hasGST = true
			}
		}
	}

	// 1. Cash-flow Stability (0 - 100)
	var cashFlowScore float64
	if hasUPI {
		// Volatility component: CV <= 0.10 is excellent (80 pts), CV >= 0.80 is high volatility (10 pts)
		volatilityPts := math.Max(10.0, 85.0-(f.InflowVolatilityCV*90.0))

		// Net flow bonus: positive net cash flow
		netFlowPts := 0.0
		if f.NetCashFlow > 0 {
			netFlowPts = 10.0
		}

		// Recurring inflow bonus
		recurringPts := f.RecurringInflowRatio * 15.0

		cashFlowScore = volatilityPts + netFlowPts + recurringPts
	} else if hasGig {
		// Gig payout volatility proxy
		cashFlowScore = math.Max(15.0, 90.0-(f.GigEarningsVolatilityCV*100.0))
	} else {
		cashFlowScore = 55.0 // Neutral prior when unobserved
	}

	// 2. Income Consistency (0 - 100)
	var incomeScore float64
	if hasGig {
		continuityPts := math.Min(40.0, float64(f.GigContinuityMonths)*15.0) // Up to 40 pts for 3+ months
		activeDaysPts := math.Min(35.0, (f.GigActiveDaysPerMonth/25.0)*35.0) // Up to 35 pts for ~25 active days/mo
		volatilityPts := math.Max(5.0, 25.0-(f.GigEarningsVolatilityCV*30.0))

		incomeScore = continuityPts + activeDaysPts + volatilityPts
	} else if hasGST {
		turnoverConsistency := math.Max(10.0, 60.0-(f.GSTTurnoverVolatilityCV*70.0))
		filingPts := f.GSTFilingConsistency * 40.0
		incomeScore = turnoverConsistency + filingPts
	} else if hasUPI {
		// Evaluated through UPI recurring inflows
		continuityPts := math.Min(40.0, float64(len(f.MonthlyInflows))*12.0)
		volatilityPts := math.Max(10.0, 35.0-(f.InflowVolatilityCV*40.0))
		recurringPts := f.RecurringInflowRatio * 25.0
		incomeScore = continuityPts + volatilityPts + recurringPts
	} else {
		incomeScore = 50.0 // Neutral prior
	}

	// 3. Payment Discipline (0 - 100)
	var paymentScore float64
	if hasUtility {
		onTimePts := f.UtilityOnTimeRatio * 75.0                       // Up to 75 pts for 100% on-time
		delayPenalty := math.Min(30.0, f.UtilityAvgDelayDays*6.0)      // Penalty for delay days
		volumeBase := math.Min(25.0, float64(f.UtilityTotalBills)*5.0) // Up to 25 pts for 5+ tracked bills

		paymentScore = onTimePts - delayPenalty + volumeBase
	} else if hasUPI {
		// Inflow-to-outflow discipline
		if f.CreditDebitRatio >= 1.2 {
			paymentScore = 72.0
		} else {
			paymentScore = 60.0
		}
	} else {
		paymentScore = 60.0 // Neutral prior
	}

	// 4. Activity Continuity (0 - 100)
	var activityScore float64
	if hasUPI || hasGig {
		activeDaysPts := 0.0
		if hasUPI {
			activeDaysPts = math.Min(50.0, f.ActiveDaysRatio*70.0)
		} else if hasGig {
			activeDaysPts = math.Min(50.0, (f.GigActiveDaysPerMonth/30.0)*50.0)
		}

		txnDensityPts := 0.0
		if f.TotalTransactions >= 20 {
			txnDensityPts = 30.0
		} else if f.TotalTransactions > 0 {
			txnDensityPts = float64(f.TotalTransactions) * 1.5
		} else if hasGig {
			txnDensityPts = 25.0
		}

		spanPts := math.Min(20.0, float64(math.Max(float64(len(f.MonthlyInflows)), float64(f.GigContinuityMonths)))*7.0)

		activityScore = activeDaysPts + txnDensityPts + spanPts
	} else {
		activityScore = 50.0
	}

	// 5. Financial Resilience (0 - 100)
	var resilienceScore float64
	if hasUPI {
		ratioPts := 0.0
		if f.CreditDebitRatio >= 2.0 {
			ratioPts = 45.0
		} else if f.CreditDebitRatio >= 1.4 {
			ratioPts = 38.0
		} else if f.CreditDebitRatio >= 1.1 {
			ratioPts = 28.0
		} else if f.CreditDebitRatio >= 1.0 {
			ratioPts = 20.0
		} else {
			ratioPts = 10.0
		}

		// Buffer relative to monthly outflow
		bufferPts := 0.0
		if f.AvgMonthlyOutflow > 0 {
			bufferRatio := f.NetCashFlow / f.AvgMonthlyOutflow
			if bufferRatio >= 1.0 {
				bufferPts = 35.0
			} else if bufferRatio > 0 {
				bufferPts = bufferRatio * 35.0
			}
		} else if f.TotalInflow > 0 {
			bufferPts = 30.0
		}

		// Recurring stability bonus
		recurringBonus := f.RecurringInflowRatio * 20.0

		resilienceScore = ratioPts + bufferPts + recurringBonus
	} else if hasGig {
		resilienceScore = math.Max(20.0, 75.0-(f.GigEarningsVolatilityCV*60.0))
	} else {
		resilienceScore = 55.0
	}

	return domain.BehavioralDimensions{
		CashFlowStability:   math.Round(clamp(cashFlowScore, 10.0, 98.0)*10) / 10,
		IncomeConsistency:   math.Round(clamp(incomeScore, 10.0, 98.0)*10) / 10,
		PaymentDiscipline:   math.Round(clamp(paymentScore, 10.0, 98.0)*10) / 10,
		ActivityContinuity:  math.Round(clamp(activityScore, 10.0, 98.0)*10) / 10,
		FinancialResilience: math.Round(clamp(resilienceScore, 10.0, 98.0)*10) / 10,
	}
}

// CalculateConfidence calculates independent data and extraction reliability score (0 - 100%)
func CalculateConfidence(evidenceList []domain.CanonicalEvidence) int {
	if len(evidenceList) == 0 {
		return 0
	}

	var sumQuality, sumExtraction, sumValidation float64
	for _, ev := range evidenceList {
		q := ev.SourceQuality
		if q <= 0 {
			q = 0.90 // Default high quality for valid standard format
		}
		e := ev.ExtractionConfidence
		if e <= 0 {
			e = 0.95 // Default high extraction confidence for structured format
		}
		v := 1.0
		if ev.Provenance.ValidationStatus == domain.ValidationPartial || ev.Provenance.ValidationStatus == domain.ValidationNeedsReview || ev.Provenance.ValidationStatus == "WARNING" {
			v = 0.80
		} else if ev.Provenance.ValidationStatus == domain.ValidationFailed || ev.Provenance.ValidationStatus == "FAILED" {
			v = 0.40
		}

		sumQuality += q
		sumExtraction += e
		sumValidation += v
	}

	n := float64(len(evidenceList))
	avgQ := sumQuality / n
	avgE := sumExtraction / n
	avgV := sumValidation / n

	// Cross-source verification bonus (>= 2 distinct sources)
	sourceTypes := make(map[domain.SourceType]bool)
	for _, ev := range evidenceList {
		sourceTypes[ev.SourceType] = true
	}
	crossScore := 0.80
	if len(sourceTypes) >= 3 {
		crossScore = 0.98
	} else if len(sourceTypes) == 2 {
		crossScore = 0.90
	}

	// Weighted confidence: 35% Quality, 30% Extraction, 20% Validation, 15% Cross-check
	confidence := (0.35 * avgQ) + (0.30 * avgE) + (0.20 * avgV) + (0.15 * crossScore)
	confInt := int(math.Round(confidence * 100))
	if confInt > 100 {
		confInt = 100
	}
	if confInt < 10 {
		confInt = 10
	}
	return confInt
}

// CalculateCoverage calculates how much relevant alternative data was available (0 - 100%)
func CalculateCoverage(evidenceList []domain.CanonicalEvidence) (int, map[string]bool) {
	breakdown := map[string]bool{
		"upi":          false,
		"gig_earnings": false,
		"utility":      false,
		"gst":          false,
		"telecom":      false,
	}

	for _, ev := range evidenceList {
		switch ev.SourceType {
		case domain.SourceUPI:
			breakdown["upi"] = true
		case domain.SourceGig:
			breakdown["gig_earnings"] = true
		case domain.SourceUtility:
			breakdown["utility"] = true
		case domain.SourceGST:
			breakdown["gst"] = true
		case domain.SourceTelecom:
			breakdown["telecom"] = true
		}
	}

	// Canonical weights for coverage
	// UPI: 35%, Gig: 25%, Utility: 20%, GST: 15%, Telecom: 5%
	totalCov := 0.0
	if breakdown["upi"] {
		totalCov += 0.35
	}
	if breakdown["gig_earnings"] {
		totalCov += 0.25
	}
	if breakdown["utility"] {
		totalCov += 0.20
	}
	if breakdown["gst"] {
		totalCov += 0.15
	}
	if breakdown["telecom"] {
		totalCov += 0.05
	}

	covInt := int(math.Round(totalCov * 100))
	if covInt > 100 {
		covInt = 100
	}
	return covInt, breakdown
}

// GenerateExplainableReasons derives evidence-backed reasons directly from calculated features
func GenerateExplainableReasons(f domain.DerivedFeatures, d domain.BehavioralDimensions, evidenceList []domain.CanonicalEvidence) ([]domain.ExplainableReason, []domain.ExplainableReason) {
	var positive []domain.ExplainableReason
	var attention []domain.ExplainableReason

	inflowMonths := len(f.MonthlyInflows)
	if inflowMonths == 0 {
		inflowMonths = 1
	}

	// 1. Inflow stability reason
	if f.TotalInflow > 0 {
		if f.InflowVolatilityCV <= 0.25 {
			positive = append(positive, domain.ExplainableReason{
				Type:          "positive",
				Title:         "Consistent Monthly Inflows",
				Summary:       fmt.Sprintf("Observed low month-over-month inflow volatility (CV: %.2f) with an average of ₹%.0f/month across %d active months.", f.InflowVolatilityCV, f.AvgMonthlyInflow, len(f.MonthlyInflows)),
				SourceType:    domain.SourceUPI,
				EvidenceRef:   "UPI Transaction Records",
				ObservedValue: fmt.Sprintf("₹%.0f avg/mo (CV %.2f)", f.AvgMonthlyInflow, f.InflowVolatilityCV),
				Impact:        "HIGH",
				Period:        fmt.Sprintf("%d observed months", len(f.MonthlyInflows)),
				Dimension:     "Cash-Flow Stability",
			})
		} else {
			attention = append(attention, domain.ExplainableReason{
				Type:          "attention",
				Title:         "Moderate Inflow Volatility",
				Summary:       fmt.Sprintf("Monthly inflows vary across the observed period (CV: %.2f), typical of seasonal or project-based informal income.", f.InflowVolatilityCV),
				SourceType:    domain.SourceUPI,
				EvidenceRef:   "UPI Transaction Records",
				ObservedValue: fmt.Sprintf("Inflow CV: %.2f", f.InflowVolatilityCV),
				Impact:        "MEDIUM",
				Period:        fmt.Sprintf("%d observed months", len(f.MonthlyInflows)),
				Dimension:     "Cash-Flow Stability",
			})
		}
	}

	// 2. Utility payment discipline reason
	if f.UtilityTotalBills > 0 {
		if f.UtilityOnTimeRatio >= 0.80 {
			positive = append(positive, domain.ExplainableReason{
				Type:          "positive",
				Title:         "Strong Payment Regularity",
				Summary:       fmt.Sprintf("Paid %d out of %d utility bills on-time (%.1f%% on-time rate) with an average delay of only %.1f days.", f.UtilityOnTimeCount, f.UtilityTotalBills, f.UtilityOnTimeRatio*100, f.UtilityAvgDelayDays),
				SourceType:    domain.SourceUtility,
				EvidenceRef:   "Utility Payment History",
				ObservedValue: fmt.Sprintf("%.1f%% on-time (%d/%d bills)", f.UtilityOnTimeRatio*100, f.UtilityOnTimeCount, f.UtilityTotalBills),
				Impact:        "HIGH",
				Period:        fmt.Sprintf("%d billing cycles", f.UtilityTotalBills),
				Dimension:     "Payment Discipline",
			})
		} else {
			attention = append(attention, domain.ExplainableReason{
				Type:          "attention",
				Title:         "Occasional Utility Payment Delays",
				Summary:       fmt.Sprintf("Observed %d late payments out of %d bills with an average delay of %.1f days.", f.UtilityTotalBills-f.UtilityOnTimeCount, f.UtilityTotalBills, f.UtilityAvgDelayDays),
				SourceType:    domain.SourceUtility,
				EvidenceRef:   "Utility Payment History",
				ObservedValue: fmt.Sprintf("%.1f days avg delay", f.UtilityAvgDelayDays),
				Impact:        "MEDIUM",
				Period:        fmt.Sprintf("%d billing cycles", f.UtilityTotalBills),
				Dimension:     "Payment Discipline",
			})
		}
	}

	// 3. Gig earnings continuity reason
	if f.GigTotalEarnings > 0 {
		if f.GigContinuityMonths >= 3 && f.GigActiveDaysPerMonth >= 15 {
			positive = append(positive, domain.ExplainableReason{
				Type:          "positive",
				Title:         "Sustained Platform Work Continuity",
				Summary:       fmt.Sprintf("Demonstrated continuous gig activity over %d months averaging %.0f active working days/month and ₹%.0f average daily earnings.", f.GigContinuityMonths, f.GigActiveDaysPerMonth, f.GigEarningsPerActiveDay),
				SourceType:    domain.SourceGig,
				EvidenceRef:   "Platform Payout Records",
				ObservedValue: fmt.Sprintf("%d months continuous, %.0f days/mo", f.GigContinuityMonths, f.GigActiveDaysPerMonth),
				Impact:        "HIGH",
				Period:        fmt.Sprintf("%d continuous months", f.GigContinuityMonths),
				Dimension:     "Income Consistency",
			})
		} else if f.GigEarningsVolatilityCV > 0.35 {
			attention = append(attention, domain.ExplainableReason{
				Type:          "attention",
				Title:         "Variable Gig Earning Periods",
				Summary:       fmt.Sprintf("Earning levels fluctuate between periods (CV: %.2f) with an average of ₹%.0f/month.", f.GigEarningsVolatilityCV, f.GigAvgMonthlyEarnings),
				SourceType:    domain.SourceGig,
				EvidenceRef:   "Platform Payout Records",
				ObservedValue: fmt.Sprintf("Earnings CV: %.2f", f.GigEarningsVolatilityCV),
				Impact:        "LOW",
				Period:        fmt.Sprintf("%d observed months", len(f.GigMonthlyEarnings)),
				Dimension:     "Income Consistency",
			})
		}
	}

	// 4. Positive Cash Buffer / Net Flow reason
	if f.TotalInflow > 0 && f.CreditDebitRatio >= 1.25 {
		positive = append(positive, domain.ExplainableReason{
			Type:          "positive",
			Title:         "Healthy Cash-Flow Buffer",
			Summary:       fmt.Sprintf("Inflows exceed outflows by a factor of %.2fx with a net positive buffer of ₹%.0f.", f.CreditDebitRatio, f.NetCashFlow),
			SourceType:    domain.SourceUPI,
			EvidenceRef:   "Cash Flow Reconciliation",
			ObservedValue: fmt.Sprintf("%.2fx inflow/outflow ratio", f.CreditDebitRatio),
			Impact:        "MEDIUM",
			Period:        fmt.Sprintf("%d active months", inflowMonths),
			Dimension:     "Financial Resilience",
		})
	}

	// 5. Activity Continuity reason
	if f.ActiveDaysCount >= 30 {
		positive = append(positive, domain.ExplainableReason{
			Type:          "positive",
			Title:         "High Transaction Engagement",
			Summary:       fmt.Sprintf("Active on %d separate calendar days across the observation period with %d total transactions.", f.ActiveDaysCount, f.TotalTransactions),
			SourceType:    domain.SourceUPI,
			EvidenceRef:   "Daily Activity Log",
			ObservedValue: fmt.Sprintf("%d active days (%d txns)", f.ActiveDaysCount, f.TotalTransactions),
			Impact:        "MEDIUM",
			Period:        fmt.Sprintf("%d active days", f.ActiveDaysCount),
			Dimension:     "Activity Continuity",
		})
	}

	return positive, attention
}

func clamp(val, min, max float64) float64 {
	if val < min {
		return min
	}
	if val > max {
		return max
	}
	return val
}
